// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3uvaXtHKzyLUrZKUT_iW8olQtxaFqwLo',
    appId: '1:553160268453:web:6f5448214dfc4390f10b4c',
    messagingSenderId: '553160268453',
    projectId: 'madinclass12',
    authDomain: 'madinclass12.firebaseapp.com',
    storageBucket: 'madinclass12.firebasestorage.app',
    measurementId: 'G-D6R60726HY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbz3_Idar0Z6y2tYU-A36lEXb-sTw-aG8',
    appId: '1:553160268453:android:0cd59b252f690278f10b4c',
    messagingSenderId: '553160268453',
    projectId: 'madinclass12',
    storageBucket: 'madinclass12.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3uvaXtHKzyLUrZKUT_iW8olQtxaFqwLo',
    appId: '1:553160268453:web:c80b09ffcbd11725f10b4c',
    messagingSenderId: '553160268453',
    projectId: 'madinclass12',
    authDomain: 'madinclass12.firebaseapp.com',
    storageBucket: 'madinclass12.firebasestorage.app',
    measurementId: 'G-RGE2W0LSV2',
  );
}
